Some debugging output

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -97,7 +97,7 @@ jobs:
       - lib-check
       - pack-charm
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
         suite: ${{ fromJSON(needs.define-matrix.outputs.suites) }}
     steps:
@@ -109,6 +109,17 @@ jobs:
         with:
           name: charm
           path: ${{ github.workspace }}/charm
+
+      - name: Check that the charm artifact made it
+        run: |
+          charm_path="${{ github.workspace }}/charm"
+          ls -l $charm_path
+          echo $(ls -l ${{ github.workspace }}/charm)
+          # fail if $charm_path/*.charm is not found
+          if [ ! -f $charm_path/*.charm ]; then
+            echo "No charm artifact found"
+            exit 1
+          fi
   
       - name: Setup LXD
         uses: canonical/setup-lxd@main
